version: "2"
plugins:
  pep8:
    enabled: true
    checks:
      E402:
        enabled: false
      E203:
        enabled: false
      W503:
        enabled: false
  radon:
    enabled: true
    config:
      python_version: 3
  sonar-python:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
          python_version: 3
